networks:
  traefik_proxy:
    external: true
    name: traefik_traefik_proxy
  homeautomation:
    external: true

volumes:
  eplzones_config:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/docker_nfs/eplzones/"

services:
  EPLZones:
    image: everythingsmarthome/everything-presence-mmwave-configurator:2.0.9
    container_name: everything-presence-mmwave-configurator
    restart: unless-stopped
    networks:
      - traefik_proxy
      - homeautomation
    env_file:
      - .env
    volumes:
      - eplzones_config:/config
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik_proxy
      - traefik.http.routers.EPLZones.rule=Host(`eplzones.viewpoint.house`)
      - traefik.http.routers.EPLZones.entrypoints=websecure
      - traefik.http.routers.EPLZones.tls.certresolver=letsencrypt
      - traefik.http.routers.EPLZones.tls.domains[0].main=eplzones.viewpoint.house
      - traefik.http.services.EPLZones.loadbalancer.server.port=3000
      - traefik.http.services.EPLZones.loadbalancer.healthcheck.path=/
      - traefik.http.services.EPLZones.loadbalancer.healthcheck.port=3000
      - homepage.group=Home Automation
      - homepage.name=EPL Zones
      - homepage.icon=mdi-home-assistant
      - homepage.href=https://eplzones.viewpoint.house
      - homepage.description=EPL Zones
