---

volumes:
  beszel_agent_data:

services:
  beszel-agent:
    # image: henrygd/beszel-agent:0.17.0
    image: henrygd/beszel-agent:0.17.0-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional, but required for NVME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: ${BLACKBIRD_KEY}
      TOKEN: ${BLACKBIRD_TOKEN}
      HUB_URL: https://beszel.viewpoint.house
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/sdj:/dev/sdj
      - /dev/nvme0:/dev/nvme0